name: example
description: Example app for flutter_cupertino package
publish_to: none
version: 0.0.1+1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_cupertino:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
